### ISSUE TITLE
X e Y invertidos

### ISSUE THREAD

**Issue by davy-ramos** [MateusAquino/BBB21-Bot#1]
Amigo, parece que os vetores Y e X estão invertidos no código, outra coisa que reparei é que o scrolldown mata todo o processo caso o site dê algum atraso, vai acabar clicando em outro participante no processo e as vezes até votando nele. Uma dica pra trabalhar sem scrolldown é simplesmente reduzindo o tamanho da página no navegador, dai caso queira votar no último participante não é necessário rolar para baixo.

Projeto tem futuro.

**Comment by MateusAquino** [comment]
Olá @davy-ramos, obrigado pelo feedback! :)

Como citei no README este projeto foi apenas para estudo, funcionando apenas no meu setup, ou seja, o delay do scrolldown até o próximo clique tava tranquilo pra mim. Quanto ao X e Y, se você veio da área de CG é comum haver a troca de nomes entre linhas (não-intuitivamente representada pelo eixo y) e colunas (eixo x), porém mesmo neste caso elas estão nas coordenadas cartesianas padrão (x, y).  
Caso queira conferir os docs do pymouse utilizando os parâmetros x e y na mesma ordem que utilizei no código, você pode conferir [clicando aqui](https://github.com/pepijndevos/PyMouse/wiki/API).  
Se precisar alterar o delay, os eixos ou até mesmo dar continuidade a estre projeto, você pode forkar este repositório e utilizar de acordo com o seu setup ou preferências :)
